services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fitnessapp-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "FitnessApp123!"
    ports:
      - "1433:1433"
    volumes:
      - fitnessapp-sqlserver-data:/var/opt/mssql

volumes:
  fitnessapp-sqlserver-data:
